### ISSUE TITLE
Issue: Pandoc version update needed on my end?

### ISSUE THREAD

**Issue by decathinator** [gmontse/DATA550_FinalProject#1]
$ make FinalProject2.html
Rscript code/render_report.R
here() starts at C:/Git/PeerReview_DATA550_FinalProject
Error: pandoc version 1.12.3 or higher is required and was not found (see the he
lp page ?rmarkdown::pandoc_available).
Execution halted

**Comment by decathinator** [comment]
all other make commands for files worked

**Comment by gmontse** [comment]
Hi Cathy! Thanks! I think the error is on your end - I also had the same issue when running make at first, and I had to update pandoc via the terminal using homebrew so you might have to do the same!
